alias mm-stop='sudo systemctl stop ModemManager'
alias mm-start='sudo systemctl start ModemManager'
alias mm-reload='sudo systemctl daemon-reload'
alias mm-restart='sudo systemctl daemon-reload && sudo systemctl restart ModemManager'
alias mm-status='sudo systemctl status ModemManager'
alias mm-log='journalctl -fu ModemManager | raffaello -f modemmanager'
alias mm-dbg='mmcli -G DEBUG'
alias mm-test='ulimit -c unlimited && sudo systemctl stop ModemManager && sudo ModemManager --debug --log-level=DEBUG'
alias mm-test-color='ulimit -c unlimited && sudo systemctl stop ModemManager && sudo ModemManager --debug --log-level=DEBUG | raffaello -f modemmanager'
