kubectl_bin: kubectl
pager: less
tabs:
    - name: Nodes
      command: get nodes -o wide
    - name: RHWA
      command: get pods -n openshift-workload-availability
    - name: SBR
      command: get pods -A -l app.kubernetes.io/name=sbd-operator
    - name: SBR-agent
      command: get daemonsets -A -l app=sbd-agent
    - name: CEO
      command: get pods -n openshift-etcd-operator
    - name: ETCD
      command: get pods -n openshift-etcd
    - name: Secrets
      command: get Secrets -A
    - name: ConfigMap
      command: get ConfigMap -A
custom_commands: []
