# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ' '
format = 'on [$symbol$branch]($style) '

[git_commit]
tag_disabled = false

[golang]
symbol = "GO "
#format = '$symbol[($version )]($style)'

[hostname]
format='[$hostname]($style) '

[time]
format = '[$time]($style) '
disabled = false

[container]
# for toolbox
style = 'bold green dimmed'
format = '[$symbol]($style) '
disabled = false

[custom.git_user]
when = "git rev-parse --is-inside-work-tree"
require_repo = true
command = "if git config user.email | grep redhat >/dev/null; then echo \" \"; else if git config user.email | grep gmail >/dev/null; then echo \" \"; else echo \" \"; fi; fi"
style = "bold yellow"
ignore_timeout = true
