# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_length = 2
truncate_to_repo = false

[git_branch]
symbol = ' '
format = 'on [$symbol$branch]($style) '

[git_commit]
tag_disabled = false

[golang]
symbol = "go "
#format = '$symbol[($version )]($style)'

[hostname]
format='[$hostname]($style) '

[time]
format = '[$time]($style) '
disabled = false
