prSections:
- title: Medik8s
  filters: is:open org:medik8s
  type: null
- title: Openshift/Release
  filters: is:open repo:openshift/release
  type: null
- title: Involved
  filters: is:open involves:@me -author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Dependabot
  filters: is:open org:medik8s dependabot
  type: null
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
repoPaths:
  openshift/*: ~/workspace/codeReviews/openshift/*
  medik8s/*: ~/workspace/codeReviews/medik8s/*
  clobrano/*: ~/workspace/codeReviews/clobrano/*
  ClusterLabs/*: ~/workspace/codeReviews/ClusterLabs/*
defaults:
  sectionsWidth: 50
  preview:
    open: false
    width: 100
  prApproveComment: /lgtm
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
  - key: J
    builtin: pageDown
  - key: K
    builtin: pageUp
  issues: []
  prs:
  - key: H
    builtin: prevSidebarTab
  - key: L
    builtin: nextSidebarTab
  - key: d
    name: sticky diff
    command: >
      gh pr diff {{.PrNumber}} --repo {{.RepoName}} | delta --side-by-side --paging=always
  - key: V
    name: approve with hold
    command: >
      gh pr review {{.PrNumber}} --repo {{.RepoName}} --approve --body $'/lgtm\ngiving the chance to get more reviews\n/hold'
  - key: O
    builtin: checkout
  - key: C
    command: >
        tmux new-window -c {{.RepoPath}} ' nvim -c ":silent Octo pr edit {{.PrNumber}}" '
  branches: []
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors: # catppuccin-frappe-yellow
    text:
      primary: "#c6d0f5"
      secondary: "#e5c890"
      inverted: "#232634"
      faint: "#b5bfe2"
      warning: "#e5c890"
      success: "#a6d189"
      error: "#e78284"
    background:
      selected: "#414559"
    border:
      primary: "#e5c890"
      secondary: "#51576d"
      faint: "#414559"
pager:
  diff: "delta --side-by-side"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
