# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # PR comments
  - trigger: "lgtmhold "
    replace: "/lgtm\nGiving a chance to get-more/close-pending reviews\n/hold"

  - trigger: "pleasereview"
    replace: "May I have a review for\n\n\nany feedback is much appreciated"

  - trigger: "!time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "[%H:%M]"

  # Smart date (e.g. !!yesterday!)
  - regex: "!!(?P<smart>.*)!"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date -d \"{{smart}}\" +%F"

  # frequent typo
  - trigger: "rwha "
    replace: "rhwa "

  # I had enough of writing long names
  - trigger: "kop "
    replace: "kubernetes operator"
  - trigger: "krp "
    replace: "kube-rbac-proxy"


  # Jira shortcuts
  - trigger: "!jira"
    replace: "https://issues.redhat.com/browse/"

  # AI prompts
  - trigger: "aicommit "
    replace: "can you write a concise commit message with an outline of most interesting changes"

  - trigger: "!junior "
    replace: "explain this to me like I was junior software developer"

  - trigger: "!summary "
    replace: "create a summary with up to 7 sections. For each section I want an introduction, a quote and a conclusion. If it is a video, I want also the timestamp and a weblink to the timestamp"

  # CI Tests
  - trigger: "citest412 "
    replace: "/test 4.12-openshift-e2e"
  - trigger: "citest413 "
    replace: "/test 4.13-openshift-e2e"
  - trigger: "citest414 "
    replace: "/test 4.14-openshift-e2e"
  - trigger: "citest415 "
    replace: "/test 4.15-openshift-e2e"
  - trigger: "citest416 "
    replace: "/test 4.16-openshift-e2e"

  # clusters
  - trigger: "aws15 "
    replace: "launch 4.15 aws"
  - trigger: "aws16 "
    replace: "launch 4.16 aws"
