[terminal]
shell = { program = "/usr/bin/zsh" }

[font]
size = 10.0
normal = { family = "Source Code Pro Medium", style = "Regular" }

[scrolling]
history = 0

[window]
decorations = "None"
dynamic_padding = true
opacity = 1.00
#startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[window.padding]
x = 10
y = 5

[general]
live_config_reload = true

import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
]
