live_config_reload = true
#shell = "/home/clobrano/workspace/script-fu/neovim-note-popup.sh"
shell = "/home/clobrano/workspace/script-fu/tmux-session-attach-or-new-2nd.sh"

import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[font]
size = 11.0
normal = { family = "Source Code Pro Medium", style = "Regular" }

[scrolling]
history = 0

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 15
y = 10
