kubectl_bin: kubectl
pager: less
refresh_interval: 5s
logs_follow_in_new_shell: true
keybindings:
    quit: q
    help: '?'
    refresh: r
    search: /
    describe: d
    logs: L
    delete: D
    edit: e
    exec: x
    port_forward: p
    scale: s
    rollout_restart: R
    yaml_view: "Y"
    json_view: J
    switch_namespace: "n"
    switch_context: c
    multi_select: ' '
    enter: enter
    escape: esc
    up: up
    down: down
    tab_next: tab
    tab_prev: shift+tab
    delete_tab: '-'
tabs:
    - name: Pods
      command: pods -A
    - name: Deployments
      command: deployments -A
    - name: Services
      command: services -A
    - name: RHWA
      command: pods -n openshift-workload-availability
    - name: SBR
      command: pods -n sbr-operator-system
    - name: Subs
      command: subs -A
    - name: Jobs
      command: jobs -A
custom_commands: []
